### ISSUE TITLE
I get error 404

### ISSUE THREAD

**Issue by tombohub** [Arshu/ASP.NET-Core-In-Fly.io#2]
Projects deploys without error, but when visiting fly.io app link I get error 404.

**Comment by Srid68** [comment]
I could not launch as https://aspnet.fly.dev since it is already used by others in fly environment.

I cloned the repository today and navigated to the root directory and executed the below command to launch a new app named as aspnet1 and able to successfully launch the default aspnet website in https://aspnet1.fly.dev.

flyctl launch 

<img width="943" alt="image" src="https://user-images.githubusercontent.com/567367/220588686-ae66ae17-22ba-43fb-bf50-d7a81f2d9f9f.png">
<img width="1097" alt="image" src="https://user-images.githubusercontent.com/567367/220588956-31f7dedd-3ccb-473e-9e93-e5e512e3f67b.png">

**Comment by tombohub** [comment]
@Srid68 yes, it's working, thank you
